```{r}
library(ecodist)
library(ggplot2)
library(vegan)
library(ConQuR)
library(doParallel)
library(MMUPHin)
library(bayesm)
library(ggpubr)
source("./function.R")
```


```{r}
# load order level data
count = read.csv("../data/count_order.csv")
count = count[,-1]

dist = read.csv("../data/dist_order.csv")
dist = as.matrix(dist[,-1])
```


```{r}
# PCoA plot
permanova_r2 <- function(distP, Y, method = "bray") {
  df.Y = as.data.frame(Y)
  Re = adonis2(distP~Y, data = df.Y)
  return(Re$R2[1])
}

## discrete
mds.plot = function(A,gl,main,colorset = "Set1",sample = "Study"){
  dist_matrix = bcdist(t(A))
  mds.stuff = cmdscale(dist_matrix, eig=T, x.ret=T)
  mds.var.per = round(mds.stuff$eig/sum(mds.stuff$eig)*100,1)
  mds.values = mds.stuff$points
  mds.data = data.frame( X=mds.values[,1],
                         Y=mds.values[,2],
                         Sample = gl)

  r2 = permanova_r2(dist_matrix,gl)
  ggplot(data=mds.data, aes(x=X, y=Y,color=Sample))+
    geom_point(size=0.2)+
    xlab(paste("PCoA1 -", mds.var.per[1], '%', sep=""))+
    ylab(paste("PCoA2 -", mds.var.per[2], '%', sep=""))+
    labs(title = main,
              subtitle = paste("R2 =",round(r2, digits = 2)))+
    theme_bw()+
    scale_color_brewer(palette=colorset)+
    theme(legend.key.height=unit(0.5,"cm"))+
    guides(color=guide_legend(title=sample))
}

## continuous
library(viridis)
mds.plot.cont = function(A,gl,main){
  dist_matrix = bcdist(t(A))
  mds.stuff = cmdscale(dist_matrix, eig=T, x.ret=T)
  mds.var.per = round(mds.stuff$eig/sum(mds.stuff$eig)*100,1)
  mds.values = mds.stuff$points
  mds.data = data.frame(X=mds.values[,1],
                         Y=mds.values[,2],
                         Signal = gl)
  r2 = permanova_r2(dist_matrix,gl)

  ggplot(data=mds.data, aes(x=X, y=Y,col=Signal))+
    geom_point(size=0.2)+
    scale_colour_gradientn(colors = viridis(10))+
    xlab(paste("PCoA1 -", mds.var.per[1], '%', sep=""))+
    ylab(paste("PCoA2 -", mds.var.per[2], '%', sep=""))+
    labs(title = main,
              subtitle = paste("R2 =",round(r2, digits = 2)))+
    theme_bw()
}
```

# pcoa: Fig2 (c)-(d)

```{r}
init_dataset = function(m,n,count,dist,k,neighbor = 5, sigma = 1, ez = 10){

  d = nrow(count) # taxa number
  O_list = list() # observed abundance
  X_list = list() # absolute abundance
  w_list = matrix(0,m,d) # measurement efficiency
  
  meta.list = list()
  meta.list1 = list()
  
  prevalence = rowSums(count!=0)
  d1 = sample(1:d,40)
  
  # A: taxa adjacency matrix
  A = matrix(0,d,d)
  for(i in 1:d){
    idx = order(dist[i,],decreasing = F)[2:(neighbor+1)]
    A[i,idx] = exp(-dist[i,idx]/sigma)
    A[idx,i] = exp(-dist[i,idx]/sigma)
  }
  D1 = diag(rowSums(A))
  L = D1-A # Laplacian matrix of taxa neighborhood matrix
  svd_res = svd(L)
  U = svd_res$u
  U = U[,(ncol(U)-k+1):(ncol(U))] # Last k eigenvectors are used in construction of measurement efficiency
  
  for(i in 1:m){
    idx1 = sample(ncol(count),n)
    X0 = as.matrix(count[,idx1])
    
    X = sapply(1:n,function(j)rdirichlet(X0[,j]+0.1))
    Y = sample(1:2,size=n,replace=TRUE,prob=c(1/2,1/2))
    X[d1,which(Y==1)] = (X[d1,which(Y==1)])*ez
    
    X_lib = X%*%diag(sample(10000:15000,n,replace = T))

    w_space = U
    weight = 1-2*runif(k)
    w = (w_space%*%as.matrix(weight))[,1]
    w = (w-min(w)+0.05)
    w = w/max(w)
    
    # Y2: uninformative label
    Y2 = as.factor(rbinom(n,1,1/2)) 
    
    
    O_list[i] = list(floor(diag(w)%*%X_lib))
    w_list[i,] = w
    X_list[i] = list(X)
    meta.list[[i]] = data.frame("Y" = sapply(Y,function(x)paste("Group",x)),"Y2" = Y2)
    meta.list1[[i]] = data.frame("Y2" = Y2)
  }
  return(list(O_list, w_list, X_list, meta.list, meta.list1))
}
```

```{r}
set.seed(3)
m = 2
n = 200
data = init_dataset(m,n,count,dist,k=10, ez=5)

O_list = data[[1]]
w_list_t = data[[2]]
X_list = data[[3]]
meta.list = data[[4]]
meta.list.sub = data[[5]]

meta = do.call("rbind",meta.list)
O = do.call(cbind,O_list)
meta$batch =as.factor(do.call(c,lapply(1:m, function(x)rep(paste("Batch",x),n))))
meta_sub = meta[,-1] # meta table without group variable Y

dataset_info = meta$batch
sample_info = meta$Y
```

```{r}
O = do.call(cbind,O_list)
p1.1 = mds.plot(O,dataset_info,"Unprocessed","Set1","Batch")
p1.2 = mds.plot(O,sample_info,"Unprocessed","Dark2","Biological Group")
```

```{r}
X = do.call(cbind,X_list)
p2.1 = mds.plot(X,dataset_info,"Truth","Set1","Batch")
p2.2 = mds.plot(X,sample_info,"Truth","Dark2","Biological Group")
```

```{r}
alpha = 0.01
beta = 1
gamma = 10
metadict_res_1 = metadict(O_list,alpha,beta,gamma,dist,meta.list = meta.list.sub) # without Y
metadict_res_2 = metadict(O_list,alpha,beta,gamma,dist,meta.list = meta.list) # with Y

p3.1 = mds.plot(metadict_res_1$X,dataset_info,"MetaDICT","Set1","Batch")
p3.2 = mds.plot(metadict_res_1$X,sample_info,"MetaDICT","Dark2","Biological Group")

p3.3 = mds.plot(metadict_res_2$X,dataset_info,"MetaDICT","Set1","Batch")
p3.4 = mds.plot(metadict_res_2$X,sample_info,"MetaDICT","Dark2","Biological Group")
```

```{r}
res_ComBatSeq_1 = sva::ComBat_seq(as.matrix(O),dataset_info,covar_mod = as.data.frame(meta_sub[,-2])) # without Y
res_ComBatSeq_2 = sva::ComBat_seq(as.matrix(O),dataset_info, covar_mod = meta[,-3]) # with Y

p5.1 = mds.plot(res_ComBatSeq_1,dataset_info,"ComBatSeq","Set1","Batch")
p5.2 = mds.plot(res_ComBatSeq_1,sample_info,"ComBatSeq","Dark2","Biological Group")

p5.3 = mds.plot(res_ComBatSeq_2,dataset_info,"ComBatSeq","Set1","Batch")
p5.4 = mds.plot(res_ComBatSeq_2,sample_info,"ComBatSeq","Dark2","Biological Group")
```

```{r}
colnames(O) = sapply(1:ncol(O),function(x)paste("Sample",x))
rownames(meta) = sapply(1:ncol(O),function(x)paste("Sample",x))
meta$batch = as.factor(meta$batch)
res_mmuphin_1 = adjust_batch(feature_abd = O,
                              batch = "batch",
                             covariates = "Y2",
                              data = meta)$feature_abd_adj
res_mmuphin_2 = adjust_batch(feature_abd = O,
                             batch = "batch",
                             covariates = c("Y","Y2"),
                             data = meta)$feature_abd_adj

p6.1 = mds.plot(res_mmuphin_1,dataset_info,"MMUPHin","Set1","Batch")
p6.2 = mds.plot(res_mmuphin_1,sample_info,"MMUPHin","Dark2","Biological Group")

p6.3 = mds.plot(res_mmuphin_2,dataset_info,"MMUPHin","Set1","Batch")
p6.4 = mds.plot(res_mmuphin_2,sample_info,"MMUPHin","Dark2","Biological Group")
```

```{r,warning=F}
# ConQuR
batchid = as.factor(do.call(c,lapply(1:m, function(x)rep(x,n))))
tax_tab = t(O)
batchid = as.factor(c(rep(1,n),rep(2,n)))
res_ConQuR_1 = ConQuR(tax_tab,batchid,batch_ref = 1,covariates = as.data.frame(meta_sub[,-2]))
meta$Y = as.factor(meta$Y)
res_ConQuR_2 = ConQuR(tax_tab,batchid,batch_ref = 1,covariates = meta[,-3])

p4.1 = mds.plot(t(res_ConQuR_1),dataset_info,"ConQuR","Set1","Batch")
p4.2 = mds.plot(t(res_ConQuR_1),sample_info,"ConQuR","Dark2","Biological Group")

p4.3 = mds.plot(t(res_ConQuR_2),dataset_info,"ConQuR","Set1","Batch")
p4.4 = mds.plot(t(res_ConQuR_2),sample_info,"ConQuR","Dark2","Biological Group")
```

```{r}
# fig 2(d)
ggarrange(p1.1,p2.1,p3.1,p4.1,p5.1,p6.1,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim1_nocov_batch.jpeg", dpi=300, units="in", width=10, height=2.5)

ggarrange(p1.2,p2.2,p3.2,p4.2,p5.2,p6.2,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim1_nocov_sample.jpeg", dpi=300, units="in", width=10, height=2.5)
```

```{r}
# fig 2(c)
ggarrange(p1.1,p2.1,p3.3,p4.3,p5.3,p6.3,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim1_cov_batch.jpeg", dpi=300, units="in", width=10, height=2.5)

ggarrange(p1.2,p2.2,p3.4,p4.4,p5.4,p6.4,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim1_cov_sample.jpeg", dpi=300, units="in", width=10, height=2.5)
```

# Fig S3

```{r}
library(bayesm)
init_dataset = function(m,n,count,dist,k,neighbor = 5, sigma = 1, ez = 10){
  
  d = nrow(count)
  O_list = list()
  X_list = list()
  meta.list = list()
  meta.list1 = list()
  
  prevalence = rowSums(count!=0)
  d1 = sample(1:d,15)
  
  A = matrix(0,d,d)
  for(i in 1:d){
    idx = order(dist[i,],decreasing = F)[2:(neighbor+1)]
    A[i,idx] = exp(-dist[i,idx]/sigma)
    A[idx,i] = exp(-dist[i,idx]/sigma)
  }
  
  D1 = diag(rowSums(A))
  L = D1-A
  svd_res = svd(L)
  U = svd_res$u
  U = U[,(ncol(U)-k+1):(ncol(U))]
  
  w_list = matrix(0,m,d)
  
  for(i in 1:m){
    Y = runif(n,1,100)
    idx1 = sample(ncol(count),n)
    X0 = as.matrix(count[,idx1])
    X = sapply(1:n,function(j)rdirichlet(X0[,j]+0.1))
    X[d1,] = t(apply(X[d1,],1,function(x)x*Y))

    X_lib = X%*%diag(sample(10000:15000,n,replace = T))

    w_space = U
    weight = 1-2*runif(k)
    w = (w_space%*%as.matrix(weight))[,1]
    w = (w-min(w)+0.05)
    w = w/max(w)
    
    Y2 = as.factor(rbinom(n,1,1/2))
    
    O_list[i] = list(floor(diag(w)%*%X_lib))
    w_list[i,] = w
    X_list[i] = list(X)
    meta.list[[i]] = data.frame("Y" = Y,"Y2" = Y2)
    meta.list1[[i]] = data.frame("Y2" = Y2)
  }
  return(list(O_list, w_list, X_list, meta.list, meta.list1))
}
```

```{r}
set.seed(2)
m = 2
n = 200
data = init_dataset(m,n,count,dist,k=10, ez=2)

O_list = data[[1]]
w_list_t = data[[2]]
X_list = data[[3]]
meta.list = data[[4]]
meta.list.sub = data[[5]]

meta = do.call("rbind",meta.list)

O = do.call(cbind,O_list)
meta$batch =as.factor(do.call(c,lapply(1:m, function(x)rep(paste("Batch",x),n))))
meta_sub = meta[,-1]
dataset_info = meta$batch
sample_info = meta$Y
```

```{r}
O = do.call(cbind,O_list)
p1.1 = mds.plot(O,dataset_info,"Unprocessed","Set1","Batch")
p1.2 = mds.plot.cont(O,sample_info,"Unprocessed")
```

```{r}
X = do.call(cbind,X_list)
p2.1 = mds.plot(X,dataset_info,"Truth","Set1","Batch")
p2.2 = mds.plot.cont(X,sample_info,"Truth")
```

```{r}
alpha = 0.01
beta = 1
gamma = 10
metadict_res_1 = metadict(O_list,alpha,beta,gamma,dist,meta.list=meta.list.sub) # without Y
metadict_res_2 = metadict(O_list,alpha,beta,gamma,dist,meta.list = meta.list) # with Y

p3.1 = mds.plot(metadict_res_1$X,dataset_info,"MetaDICT","Set1","Batch")
p3.2 = mds.plot.cont(metadict_res_1$X,sample_info,"MetaDICT")

p3.3 = mds.plot(metadict_res_2$X,dataset_info,"MetaDICT","Set1","Batch")
p3.4 = mds.plot.cont(metadict_res_2$X,sample_info,"MetaDICT")
```

```{r}
res_ComBatSeq_1 = sva::ComBat_seq(as.matrix(O),dataset_info, covar_mod = as.data.frame(meta_sub[,-2]))
res_ComBatSeq_2 = sva::ComBat_seq(as.matrix(O),dataset_info,  covar_mod = meta[,-3])

p5.1 = mds.plot(res_ComBatSeq_1,dataset_info,"ComBatSeq","Set1","Batch")
p5.2 = mds.plot.cont(res_ComBatSeq_1,sample_info,"ComBatSeq")

p5.3 = mds.plot(res_ComBatSeq_2,dataset_info,"ComBatSeq","Set1","Batch")
p5.4 = mds.plot.cont(res_ComBatSeq_2,sample_info,"ComBatSeq")
```

```{r}
colnames(O) = sapply(1:ncol(O),function(x)paste("Sample",x))
rownames(meta) = sapply(1:ncol(O),function(x)paste("Sample",x))
meta$batch = as.factor(meta$batch)
res_mmuphin_1 = adjust_batch(feature_abd = O,
                              batch = "batch",
                             covariates = "Y2",
                              data = meta)$feature_abd_adj
res_mmuphin_2 = adjust_batch(feature_abd = O,
                             batch = "batch",
                             covariates = c("Y","Y2"),
                             data = meta)$feature_abd_adj

p6.1 = mds.plot(res_mmuphin_1,dataset_info,"MMUPHin","Set1","Batch")
p6.2 = mds.plot.cont(res_mmuphin_1,sample_info,"MMUPHin")

p6.3 = mds.plot(res_mmuphin_2,dataset_info,"MMUPHin","Set1","Batch")
p6.4 = mds.plot.cont(res_mmuphin_2,sample_info,"MMUPHin")
```

```{r,warning=F}
# ConQuR
tax_tab = t(O)
batchid = as.factor(do.call(c,lapply(1:m, function(x)rep(x,n))))
res_ConQuR_1 = ConQuR(tax_tab,batchid,batch_ref = 1,covariates = meta_sub[,-2])

res_ConQuR_2 = ConQuR(tax_tab,batchid,batch_ref = 1,covariates = meta[,-3])

p4.1 = mds.plot(t(res_ConQuR_1),dataset_info,"ConQuR","Set1","Batch")
p4.2 = mds.plot.cont(t(res_ConQuR_1),sample_info,"ConQuR")

p4.3 = mds.plot(t(res_ConQuR_2),dataset_info,"ConQuR","Set1","Batch")
p4.4 = mds.plot.cont(t(res_ConQuR_2),sample_info,"ConQuR")
```

```{r}
# S3 (b)
ggarrange(p1.1,p2.1,p3.1,p4.1,p5.1,p6.1,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim2_nocov_batch.jpeg", dpi=300, units="in", width=10, height=2.5)

ggarrange(p1.2,p2.2,p3.2,p4.2,p5.2,p6.2,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim2_nocov_sample.jpeg", dpi=300, units="in", width=10, height=2.5)
```

```{r}
# fig S3 (a)
ggarrange(p1.1,p2.1,p3.3,p4.3,p5.3,p6.3,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim2_cov_batch.jpeg", dpi=300, units="in", width=10, height=2.5)

ggarrange(p1.2,p2.2,p3.4,p4.4,p5.4,p6.4,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim2_cov_sample.jpeg", dpi=300, units="in", width=10, height=2.5)
```

# Fig 3

```{r}
init_dataset = function(m,n,count,dist,k,neighbor = 5, sigma = 1, ez = 10, eta = c(1/2,1/2)){
  
  d = nrow(count)
  O_list = list()
  X_list = list()
  meta.list = list()
  meta.list1 = list()
  
  prevalence = rowSums(count!=0)
  d1 = sample(1:d,40)
  
  A = matrix(0,d,d)
  for(i in 1:d){
    idx = order(dist[i,],decreasing = F)[2:(neighbor+1)]
    A[i,idx] = exp(-dist[i,idx]/sigma)
    A[idx,i] = exp(-dist[i,idx]/sigma)
  }
  D1 = diag(rowSums(A))
  L = D1-A
  svd_res = svd(L)
  U = svd_res$u
  U = U[,(ncol(U)-k+1):(ncol(U))]
  
  w_list = matrix(0,m,d)
  for(i in 1:m){
    idx1 = sample(ncol(count),n)
    X0 = as.matrix(count[,idx1])
    X0 = t(t(X0)/colSums(X0))
    Y = sample(1:2,size=n,replace=TRUE,prob=c(eta[i],1-eta[i]))
    X0[d1,which(Y==1)] = (X0[d1,which(Y==1)]+0.1)*ez
    X = sapply(1:n,function(j)rdirichlet(X0[,j]))

    X_lib = X%*%diag(sample(1000:1500,n,replace = T))
    
    w_space = U
    weight = 1-2*runif(k)
    w = (w_space%*%as.matrix(weight))[,1]
    w = (w-min(w)+0.05)
    w = w/max(w)
    
    Y2 = as.factor(rbinom(n,1,1/2))
    O_list[i] = list(floor(diag(w)%*%X_lib))
    w_list[i,] = w
    X_list[i] = list(floor(X_lib))
    
    meta.list[[i]] = data.frame("Y" = sapply(Y,function(x)paste("Group",x)),"Y2" = Y2)
    meta.list1[[i]] = data.frame("Y2" = Y2)
  }
  return(list(O_list, w_list, X_list, meta.list, meta.list1))
}
```

```{r}
set.seed(2)
m = 2
n = 200

data = init_dataset(m,n,count,dist,k=10, ez=10, eta = c(1/6,5/6))

O_list = data[[1]]
w_list_t = data[[2]]
X_list = data[[3]]
meta.list = data[[4]]
meta.list.sub = data[[5]]

meta = do.call("rbind",meta.list)

meta$batch =as.factor(do.call(c,lapply(1:m, function(x)rep(paste("Batch",x),n))))
meta_sub = meta[,-1]
dataset_info = meta$batch
sample_info = meta$Y
```

```{r}
X_list = data[[3]]
X_t = do.call(cbind,X_list)
p2.1 = mds.plot(X_t,dataset_info,"Truth","Set1","Batch")
p2.2 = mds.plot(X_t,sample_info,"Truth","Dark2","Biological Group")
```

```{r}
alpha = 1
beta = 0.1
gamma = 10
metadict_res_1 = metadict(X_list,alpha,beta,gamma,dist,meta.list = meta.list.sub) # without Y

metadict_res_2 = metadict(X_list,alpha,beta,gamma,dist,meta.list = meta.list) # with Y

p3.1 = mds.plot(metadict_res_1$X,dataset_info,"MetaDICT","Set1","Batch")
p3.2 = mds.plot(metadict_res_1$X,sample_info,"MetaDICT","Dark2","Biological Group")

p3.3 = mds.plot(metadict_res_2$X,dataset_info,"MetaDICT","Set1","Batch")
p3.4 = mds.plot(metadict_res_2$X,sample_info,"MetaDICT","Dark2","Biological Group")
```

```{r}
res_ComBatSeq_1 = sva::ComBat_seq(as.matrix(X_t),dataset_info,covar_mod = as.data.frame(meta_sub[,-2]))
res_ComBatSeq_2 = sva::ComBat_seq(as.matrix(X_t),dataset_info, covar_mod = meta[,-3])

p5.1 = mds.plot(res_ComBatSeq_1,dataset_info,"ComBatSeq","Set1","Batch")
p5.2 = mds.plot(res_ComBatSeq_1,sample_info,"ComBatSeq","Dark2","Biological Group")

p5.3 = mds.plot(res_ComBatSeq_2,dataset_info,"ComBatSeq","Set1","Batch")
p5.4 = mds.plot(res_ComBatSeq_2,sample_info,"ComBatSeq","Dark2","Biological Group")
```

```{r}
colnames(X_t) = sapply(1:ncol(O),function(x)paste("Sample",x))
rownames(meta) = sapply(1:ncol(O),function(x)paste("Sample",x))
meta$batch = as.factor(batchid)
res_mmuphin_1 = adjust_batch(feature_abd = X_t,
                              batch = "batch",
                             covariates = "Y2",
                              data = meta)$feature_abd_adj
res_mmuphin_2 = adjust_batch(feature_abd = X_t,
                             batch = "batch",
                             covariates = c("Y","Y2"),
                             data = meta)$feature_abd_adj

p6.1 = mds.plot(res_mmuphin_1,dataset_info,"MMUPHin","Set1","Batch")
p6.2 = mds.plot(res_mmuphin_1,sample_info,"MMUPHin","Dark2","Biological Group")

p6.3 = mds.plot(res_mmuphin_2,dataset_info,"MMUPHin","Set1","Batch")
p6.4 = mds.plot(res_mmuphin_2,sample_info,"MMUPHin","Dark2","Biological Group")
```

```{r,warning=F}
# ConQuR
tax_tab = t(X_t)
batchid = as.factor(do.call(c,lapply(1:m, function(x)rep(x,n))))
res_ConQuR_1 = ConQuR(tax_tab,batchid,batch_ref = 1,covariates = as.data.frame(meta_sub[,-2]))

meta$Y = as.factor(meta$Y)
res_ConQuR_2 = ConQuR(tax_tab,batchid,batch_ref = 1,covariates = meta[,-3])

p4.1 = mds.plot(t(res_ConQuR_1),dataset_info,"ConQuR","Set1","Batch")
p4.2 = mds.plot(t(res_ConQuR_1),sample_info,"ConQuR","Dark2","Biological Group")

p4.3 = mds.plot(t(res_ConQuR_2),dataset_info,"ConQuR","Set1","Batch")
p4.4 = mds.plot(t(res_ConQuR_2),sample_info,"ConQuR","Dark2","Biological Group")
```

```{r}
# fig 3 (b)
ggarrange(p2.1,p3.1,p4.1,p5.1,p6.1,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim4_nocov_batch.jpeg", dpi=300, units="in", width=10, height=2.5)

ggarrange(p2.2,p3.2,p4.2,p5.2,p6.2,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim4_nocov_sample.jpeg", dpi=300, units="in", width=10, height=2.5)
```

```{r}
# fig 3 (c)
ggarrange(p2.1,p3.3,p4.3,p5.3,p6.3,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim4_cov_batch.jpeg", dpi=300, units="in", width=10, height=2.5)

ggarrange(p2.2,p3.4,p4.4,p5.4,p6.4,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim4_cov_sample.jpeg", dpi=300, units="in", width=10, height=2.5)
```

# Fig S4

```{r}
library(bayesm)
init_dataset = function(m,n,count,dist,k,neighbor = 5, sigma = 1, ez = 10, eta = c(1/4,3/4)){
  
  d = nrow(count)
  O_list = list()
  X_list = list()
  meta.list = list()
  meta.list1 = list()
  w_list = matrix(0,m,d)
  
  prevalence = rowSums(count!=0)
  d1 = sample(1:d,40)
  
  A = matrix(0,d,d)
  for(i in 1:d){
    idx = order(dist[i,],decreasing = F)[2:(neighbor+1)]
    A[i,idx] = exp(-dist[i,idx]/sigma)
    A[idx,i] = exp(-dist[i,idx]/sigma)
  }
  
  D1 = diag(rowSums(A))
  L = D1-A
  svd_res = svd(L)
  U = svd_res$u
  U = U[,(ncol(U)-k+1):(ncol(U))]
  
  for(i in 1:m){
    idx1 = sample(ncol(count),n)
    X0 = as.matrix(count[,idx1])
    X = sapply(1:n,function(j)rdirichlet(X0[,j]+0.1))
    Y = sample(1:2,size=n,replace=TRUE,prob=c(eta[i],1-eta[i]))
    X[d1,which(Y==1)] = (X[d1,which(Y==1)])*ez
    
    X_lib = X%*%diag(sample(10000:11000,n,replace = T))
    
    w_space = U
    weight = 1-2*runif(k)
    w = (w_space%*%as.matrix(weight))[,1]
    w = (w-min(w)+0.05)
    w = w/max(w)
    
    Y2 = as.factor(rbinom(n,1,1/2))
    O_list[i] = list(floor(diag(w)%*%X_lib))
    w_list[i,] = w
    X_list[i] = list(X)
    meta.list[[i]] = data.frame("Y" = sapply(Y,function(x)paste("Group",x)),"Y2" = Y2)
    meta.list1[[i]] = data.frame("Y2" = Y2)
  }
  return(list(O_list, w_list, X_list, meta.list, meta.list1))
}
```

```{r}
set.seed(3)
m = 2
n = 200
data = init_dataset(m,n,count,dist,k=10, ez=5)

O_list = data[[1]]
w_list_t = data[[2]]
X_list = data[[3]]
meta.list = data[[4]]
meta.list.sub = data[[5]]

meta = do.call("rbind",meta.list)

O = do.call(cbind,O_list)
meta$batch =as.factor(do.call(c,lapply(1:m, function(x)rep(paste("Batch",x),n))))
meta_sub = meta[,-1]
dataset_info = meta$batch
sample_info = meta$Y
```

```{r}
O = do.call(cbind,O_list)
p1.1 = mds.plot(O,dataset_info,"Unprocessed","Set1","Batch")
p1.2 = mds.plot(O,sample_info,"Unprocessed","Dark2","Biological Group")
```

```{r}
X = do.call(cbind,X_list)
p2.1 = mds.plot(X,dataset_info,"Truth","Set1","Batch")
p2.2 = mds.plot(X,sample_info,"Truth","Dark2","Biological Group")
```

```{r}
alpha = 1.5
beta = 0.1
gamma = 10
metadict_res_1 = metadict(O_list,alpha,beta,gamma,dist,meta.list = meta.list.sub) # without Y

metadict_res_2 = metadict(O_list,alpha,beta,gamma,dist,meta.list = meta.list) # with Y

p3.1 = mds.plot(metadict_res_1$X,dataset_info,"MetaDICT","Set1","Batch")
p3.2 = mds.plot(metadict_res_1$X,sample_info,"MetaDICT","Dark2","Biological Group")

p3.3 = mds.plot(metadict_res_2$X,dataset_info,"MetaDICT","Set1","Batch")
p3.4 = mds.plot(metadict_res_2$X,sample_info,"MetaDICT","Dark2","Biological Group")
```

```{r}
res_ComBatSeq_1 = sva::ComBat_seq(as.matrix(O),dataset_info,covar_mod = as.data.frame(meta_sub[,-2]))
res_ComBatSeq_2 = sva::ComBat_seq(as.matrix(O),dataset_info, covar_mod = meta[,-3])

p5.1 = mds.plot(res_ComBatSeq_1,dataset_info,"ComBatSeq","Set1","Batch")
p5.2 = mds.plot(res_ComBatSeq_1,sample_info,"ComBatSeq","Dark2","Biological Group")

p5.3 = mds.plot(res_ComBatSeq_2,dataset_info,"ComBatSeq","Set1","Batch")
p5.4 = mds.plot(res_ComBatSeq_2,sample_info,"ComBatSeq","Dark2","Biological Group")
```

```{r}
colnames(O) = sapply(1:ncol(O),function(x)paste("Sample",x))
rownames(meta) = sapply(1:ncol(O),function(x)paste("Sample",x))
meta$batch = as.factor(meta$batch)
res_mmuphin_1 = adjust_batch(feature_abd = O,
                              batch = "batch",
                             covariates = "Y2",
                              data = meta)$feature_abd_adj
res_mmuphin_2 = adjust_batch(feature_abd = O,
                             batch = "batch",
                             covariates = c("Y","Y2"),
                             data = meta)$feature_abd_adj

p6.1 = mds.plot(res_mmuphin_1,dataset_info,"MMUPHin","Set1","Batch")
p6.2 = mds.plot(res_mmuphin_1,sample_info,"MMUPHin","Dark2","Biological Group")

p6.3 = mds.plot(res_mmuphin_2,dataset_info,"MMUPHin","Set1","Batch")
p6.4 = mds.plot(res_mmuphin_2,sample_info,"MMUPHin","Dark2","Biological Group")
```

```{r,warning=F}
# ConQuR
tax_tab = t(O)
batchid = as.factor(do.call(c,lapply(1:m, function(x)rep(x,n))))
res_ConQuR_1 = ConQuR(tax_tab,batchid,batch_ref = 1,covariates = as.data.frame(meta_sub[,-2]))

meta$Y = as.factor(meta$Y)
res_ConQuR_2 = ConQuR(tax_tab,batchid,batch_ref = 1,covariates = meta[,-3])

p4.1 = mds.plot(t(res_ConQuR_1),dataset_info,"ConQuR","Set1","Batch")
p4.2 = mds.plot(t(res_ConQuR_1),sample_info,"ConQuR","Dark2","Biological Group")

p4.3 = mds.plot(t(res_ConQuR_2),dataset_info,"ConQuR","Set1","Batch")
p4.4 = mds.plot(t(res_ConQuR_2),sample_info,"ConQuR","Dark2","Biological Group")
```

```{r}
# fig S4 (b)
ggarrange(p1.1,p2.1,p3.1,p4.1,p5.1,p6.1,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim3_nocov_batch.jpeg", dpi=300, units="in", width=10, height=2.5)

ggarrange(p1.2,p2.2,p3.2,p4.2,p5.2,p6.2,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim3_nocov_sample.jpeg", dpi=300, units="in", width=10, height=2.5)
```

```{r}
# fig S4 (a)
ggarrange(p1.1,p2.1,p3.3,p4.3,p5.3,p6.3,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim3_cov_batch.jpeg", dpi=300, units="in", width=10, height=2.5)

ggarrange(p1.2,p2.2,p3.4,p4.4,p5.4,p6.4,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim3_cov_sample.jpeg", dpi=300, units="in", width=10, height=2.5)
```

# Fig S5

```{r}
library(bayesm)
init_dataset = function(m,n,count,dist,k,neighbor = 5, sigma = 1, ez = 10, eta = c(1/4,3/4)){
  d = nrow(count)
  O_list = list()
  X_list = list()
  meta.list = list()
  meta.list1 = list()
  
  prevalence = rowSums(count!=0)
  
  d1 = sample(1:d,40)
  
  A = matrix(0,d,d)
  for(i in 1:d){
    idx = order(dist[i,],decreasing = F)[2:(neighbor+1)]
    A[i,idx] = exp(-dist[i,idx]/sigma)
    A[idx,i] = exp(-dist[i,idx]/sigma)
  }
  D1 = diag(rowSums(A))
  L = D1-A
  svd_res = svd(L)
  U = svd_res$u
  U = U[,(ncol(U)-k+1):(ncol(U))]
  
  w_list = matrix(0,m,d)
  
  for(i in 1:m){
    idx1 = sample(ncol(count),n)
    X0 = as.matrix(count[,idx1])
    X = sapply(1:n,function(j)rdirichlet(X0[,j]+0.1))
    Y = sample(1:2,size=n,replace=TRUE,prob=c(eta[i],1-eta[i]))
    X[d1,which(Y==1)] = (X[d1,which(Y==1)])*ez
    
    X_lib = X%*%diag(sample(10000:10000,n,replace = T))
    
    w_space = U
    weight = 1-2*runif(k)
    w = (w_space%*%as.matrix(weight))[,1]
    w = (w-min(w)+0.05)
    w = w/max(w)
    
    Y2 = as.factor(rbinom(n,1,1/2))
    O_list[i] = list(floor(diag(w)%*%X_lib))
    w_list[i,] = w
    X_list[i] = list(X)
    
    meta.list[[i]] = data.frame("Y" = sapply(Y,function(x)paste("Group",x)),"Y2" = Y2)
    meta.list1[[i]] = data.frame("Y2" = Y2)
  }
  
  return(list(O_list, w_list, X_list, meta.list, meta.list1))
}
```

```{r}
set.seed(3)
m = 2
n = 200
data = init_dataset(m,n,count,dist,k=10, ez=3, eta = c(1,0))

O_list = data[[1]]
w_list_t = data[[2]]
X_list = data[[3]]
meta.list = data[[4]]
meta.list.sub = data[[5]]

meta = do.call("rbind",meta.list)

O = do.call(cbind,O_list)
X = do.call(cbind,X_list)

meta$batch =as.factor(do.call(c,lapply(1:m, function(x)rep(paste("Batch",x),n))))
meta_sub = meta[,-1]

dataset_info = meta$batch
sample_info = meta$Y
```

```{r}
O = do.call(cbind,O_list)
p1.1 = mds.plot(O,dataset_info,"Unprocessed","Set1","Batch")
p1.2 = mds.plot(O,sample_info,"Unprocessed","Dark2","Biological Group")
```

```{r}
p2.1 = mds.plot(X,dataset_info,"Truth","Set1","Batch")
p2.2 = mds.plot(X,sample_info,"Truth","Dark2","Biological Group")
```

```{r}
alpha = 5
beta = 0.1
gamma = 10
metadict_res_1 = metadict(O_list,alpha,beta,gamma,dist,meta.list = meta.list.sub) # without cov

p3.1 = mds.plot(metadict_res_1$X,dataset_info,"MetaDICT","Set1","Batch")
p3.2 = mds.plot(metadict_res_1$X,sample_info,"MetaDICT","Dark2","Biological Group")
```

```{r}
res_ComBatSeq_1 = sva::ComBat_seq(as.matrix(O),dataset_info,covar_mod = as.data.frame(meta_sub[,-2]))

p5.1 = mds.plot(res_ComBatSeq_1,dataset_info,"ComBatSeq","Set1","Batch")
p5.2 = mds.plot(res_ComBatSeq_1,sample_info,"ComBatSeq","Dark2","Biological Group")
```

```{r}
colnames(O) = sapply(1:ncol(O),function(x)paste("Sample",x))
rownames(meta) = sapply(1:ncol(O),function(x)paste("Sample",x))
meta$batch = as.factor(meta$batch)
res_mmuphin_1 = adjust_batch(feature_abd = O,
                              batch = "batch",
                             covariates = "Y2",
                              data = meta)$feature_abd_adj

p6.1 = mds.plot(res_mmuphin_1,dataset_info,"MMUPHin","Set1","Batch")
p6.2 = mds.plot(res_mmuphin_1,sample_info,"MMUPHin","Dark2","Biological Group")
```

```{r,warning=F}
# ConQuR
tax_tab = t(O)
batchid = as.factor(do.call(c,lapply(1:m, function(x)rep(x,n))))
res_ConQuR_1 = ConQuR(tax_tab,batchid,batch_ref = 1,covariates = as.data.frame(meta_sub[,-2]))

p4.1 = mds.plot(t(res_ConQuR_1),dataset_info,"ConQuR","Set1","Batch")
p4.2 = mds.plot(t(res_ConQuR_1),sample_info,"ConQuR","Dark2","Biological Group")
```

```{r}
# fig S5
ggarrange(p1.1,p2.1,p3.1,p4.1,p5.1,p6.1,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim5_nocov_batch.jpeg", dpi=300, units="in", width=10, height=2.5)

ggarrange(p1.2,p2.2,p3.2,p4.2,p5.2,p6.2,common.legend = TRUE,nrow=1,legend="bottom")
ggsave("../fig/pcoa_sim5_nocov_sample.jpeg", dpi=300, units="in", width=10, height=2.5)
```
