
```{r}
library(ConQuR)
library(doParallel)
library(MMUPHin)
source("./function.R")
```

```{r}
# load order level data
count = read.csv("../data/count_order.csv")
count = count[,-1]

dist = read.csv("../data/dist_order.csv")
dist = as.matrix(dist[,-1])
```

```{r}
init_dataset = function(m,n,count,dist,k,neighbor = 5, sigma = 1, ez = 10, lib_var = T){
  d = nrow(count)
  O_list = list()
  X_list = list()
  meta.list = list()

  taxagroup = sample(1:5,size=d,replace=TRUE,prob=c(1/5,1/5,1/5,1/5,1/5))

  A = matrix(0,d,d)
  for(i in 1:d){
    idx = order(dist[i,],decreasing = F)[2:(neighbor+1)]
    A[i,idx] = exp(-dist[i,idx]/sigma)
    A[idx,i] = exp(-dist[i,idx]/sigma)
  }
  
  D1 = diag(rowSums(A))
  L = D1-A
  svd_res = svd(L)
  U = svd_res$u
  U = U[,(ncol(U)-k+1):(ncol(U))]
  w_list = matrix(0,m,d)
  
  for(i in 1:m){
    idx1 = sample(ncol(count),n)
    X = as.matrix(count[,idx1])
    Y = sample(1:4,size=n,replace=TRUE,prob=c(1/4,1/4,1/4,1/4))
    
    X[which(taxagroup == 2),which(Y==1)] = (X[which(taxagroup == 2),which(Y==1)]+1)*ez
    X[which(taxagroup == 3),which(Y==2)] = (X[which(taxagroup == 3),which(Y==2)]+1)*ez
    X[which(taxagroup == 4),which(Y==3)] = (X[which(taxagroup == 4),which(Y==3)]+1)*ez
    X[which(taxagroup == 5),which(Y==4)] = (X[which(taxagroup == 5),which(Y==4)]+1)*ez

    if(lib_var){
      if(i%%2==1){
        X_lib = X%*%diag(sample(100:500,n,replace = T))
      }else{
        X_lib = X%*%diag(sample(10:50,n,replace = T))
        }
    }
    
    w_space = U
    weight = 1-2*runif(k)
    w = (w_space%*%as.matrix(weight))[,1]
    w = (w-min(w)+0.05)
    w = w/max(w)
    
    O_list[i] = list(floor(diag(w)%*%X_lib))
    w_list[i,] = w
    X_list[i] = list(X)
    meta.list[[i]] = data.frame("Y" = sapply(Y,function(x)paste("Subpopulation",x)))
  }
  return(list(O_list, w_list, X_list, meta.list, taxagroup))
}
```

```{r}
set.seed(3)
m = 5
n = 50

data = init_dataset(m,n,count,dist,k=10, ez=50)
w_list_t = data[[2]]
O_list = data[[1]]
meta.list = data[[4]]
meta = do.call("rbind",meta.list)
batchid = as.factor(do.call(c,lapply(1:m, function(x)rep(x,n))))
O = do.call(cbind,O_list)
X_t = do.call(cbind,data[[3]])
diff_set = data[[5]]
```

```{r}
alpha = 1
beta = 0.1
gamma = 1
metadict_res = metadict(O_list,alpha,beta,gamma,dist,meta.list)
```

```{r}
D = metadict_res$D
diff_set = sapply(data[[5]], function(i)paste("Microbial Community",i))
```


## taxa community detection (S4a)

```{r}
set.seed(2024)
res = community_detection(D[,1:50],K = 10)
taxa_res_metadict = as.factor(res$cluster)
g = res$graph
library(ggraph)
p1 = ggraph(g, layout = "stress") + 
   geom_edge_fan(alpha = 0.05, show.legend = FALSE) + 
    geom_node_point(aes(color = taxa_res_metadict, shape = as.factor(diff_set)),size = 0.5) + 
    theme_bw()+
  xlab("")+
  ylab("")+
  labs(title = "MetaDICT",subtitle = paste("ARI =",round(adjustedRandIndex(taxa_res_metadict,diff_set), digits = 2)))+
  guides(color = "none", shape = guide_legend(title="Truth"))
```


```{r}
set.seed(2024)
res = community_detection(O,K=10)
taxa_res_unprocessed = as.factor(res$cluster)
g = res$graph
library(ggraph)
p3 = ggraph(g, layout = "stress") + 
   geom_edge_fan(alpha = 0.05, show.legend = FALSE) + 
    geom_node_point(aes(color = taxa_res_unprocessed, shape = as.factor(diff_set)),size = 0.5) + 
    theme_bw()+
  xlab("")+
  ylab("")+
  labs(title = "Unprocessed",subtitle = paste("ARI =",round(adjustedRandIndex(taxa_res_unprocessed,diff_set), digits = 2)))+
  guides(color = "none", shape = guide_legend(title="Truth"))
```


```{r}
set.seed(2024)
res = community_detection(O_list[[5]],K=10)
taxa_res_single = as.factor(res$cluster)
g = res$graph
library(ggraph)
p2 = ggraph(g, layout = "stress") + 
   geom_edge_fan(alpha = 0.05, show.legend = FALSE) + 
    geom_node_point(aes(color = taxa_res_single, shape = as.factor(diff_set)),size = 0.5) + 
    theme_bw()+
  xlab("")+
  ylab("")+
  labs(title = "Single Dataset",subtitle = paste("ARI =",round(adjustedRandIndex(taxa_res_single,diff_set), digits = 2)))+
  guides(color = "none", shape = guide_legend(title="Truth"))
```


```{r}
set.seed(2024)
res_ComBatSeq = sva::ComBat_seq(as.matrix(O),batchid, covar_mod = meta)


res = community_detection(res_ComBatSeq,K=10)
taxa_res_combatseq = as.factor(res$cluster)
g = res$graph
library(ggraph)
p4 = ggraph(g, layout = "stress") + 
   geom_edge_fan(alpha = 0.05, show.legend = FALSE) + 
    geom_node_point(aes(color = taxa_res_combatseq, shape = as.factor(diff_set)),size = 0.5) + 
    theme_bw()+
  xlab("")+
  ylab("")+
  labs(title = "ComBatSeq",subtitle = paste("ARI =",round(adjustedRandIndex(taxa_res_combatseq,diff_set), digits = 2)))+
  guides(color = "none", shape = guide_legend(title="Truth"))
```


```{r}
set.seed(2024)
colnames(O) = sapply(1:ncol(O),function(x)paste("Sample",x))
rownames(meta) = sapply(1:ncol(O),function(x)paste("Sample",x))
meta$batch = as.factor(batchid)

res_mmuphin = adjust_batch(feature_abd = O,
                            batch = "batch",
                            covariates = c("Y"),
                            data = meta)$feature_abd_adj


res = community_detection(res_mmuphin,K=10)
taxa_res_mmuphin = as.factor(res$cluster)
g = res$graph
library(ggraph)
p5 = ggraph(g, layout = "stress") + 
   geom_edge_fan(alpha = 0.05, show.legend = FALSE) + 
    geom_node_point(aes(color = taxa_res_mmuphin, shape = as.factor(diff_set)),size = 0.5) + 
    theme_bw()+
  xlab("")+
  ylab("")+
  labs(title = "MMUPHin",subtitle = paste("ARI =",round(adjustedRandIndex(taxa_res_mmuphin,diff_set), digits = 2)))+
  guides(color = "none", shape = guide_legend(title="Truth"))
```


```{r}
set.seed(2024)
tax_tab = t(O)
res_conqur = ConQuR(tax_tab,as.factor(batchid),batch_ref = 1,covariates = as.factor(meta$Y))


res = community_detection(t(res_conqur),K=10)
taxa_res_conqur = as.factor(res$cluster)
g = res$graph
library(ggraph)
p6 = ggraph(g, layout = "stress") + 
   geom_edge_fan(alpha = 0.05, show.legend = FALSE) + 
    geom_node_point(aes(color = taxa_res_conqur, shape = as.factor(diff_set)),size = 0.5) + 
    theme_bw()+
  xlab("")+
  ylab("")+
  labs(title = "ConQuR",subtitle = paste("ARI =",round(adjustedRandIndex(taxa_res_conqur,diff_set), digits = 2)))+
  guides(color = "none", shape = guide_legend(title="Truth"))
```


```{r}
library(ggpubr)
ggarrange(p1,p2,p3,p4,p5,p6,common.legend = TRUE,nrow=1,legend="bottom")
#ggsave("../fig/taxa_cluster_newmethod.jpeg", dpi=300, units="in", width=10, height=2.5)
```

# subpopulation detection

```{r}
set.seed(2024)
library(ggraph)
R_list = metadict_res$R
R = do.call(cbind,R_list)
sample_res = community_detection(t(R),K=50)
sample_res_metadict = as.factor(sample_res$cluster)
g2 = sample_res$graph
```

```{r}
library(ggforce)
p1 = ggraph(g2, layout = "stress") + 
    geom_node_point(aes(color = as.factor(sample_res$cluster), shape = meta$Y),size = 0.5) +
    theme_bw()+
  xlab("")+
  ylab("")+
    labs(title = "MetaDICT",subtitle = paste("ARI =",round(adjustedRandIndex(sample_res$cluster,meta$Y), digits = 2)))+
  guides(color = "none", shape = guide_legend(title="Truth"))
```

```{r}
set.seed(2024)
c_raw_s = community_detection(t(O),K=50)
sample_res_unprocessed = as.factor(c_raw_s$cluster)
p3 = ggraph(c_raw_s$g, layout = "stress") + 
    geom_node_point(aes(color = as.factor(c_raw_s$cluster), shape = as.factor(meta$Y)),size = 0.5) + 
    theme_bw()+
  xlab("")+
  ylab("")+
  labs(title = "Unprocessed",subtitle = paste("ARI =",round(adjustedRandIndex(c_raw_s$cluster,meta$Y), digits = 2)))+
  guides(color = "none", shape = guide_legend(title="Truth"))
```

```{r}
set.seed(2024)
c_combatseq_s = community_detection(t(res_ComBatSeq),K=50)
sample_res_combatseq = as.factor(c_combatseq_s$cluster)

p4 = ggraph(c_combatseq_s$g, layout = "stress") + 
    geom_node_point(aes(color = as.factor(c_combatseq_s$cluster), shape = as.factor(meta$Y)),size = 0.5) + 
    theme_bw()+
  xlab("")+
  ylab("")+
  labs(title = "ComBatSeq",subtitle = paste("ARI =",round(adjustedRandIndex(c_combatseq_s$cluster,meta$Y), digits = 2)))+
  guides(color = "none", shape = guide_legend(title="Truth"))
```

```{r}
set.seed(2024)
c_mmuphin_s = community_detection(t(res_mmuphin),K=50)
sample_res_mmuphin = as.factor(c_mmuphin_s$cluster)
p5 = ggraph(c_mmuphin_s$g, layout = "stress") + 
    geom_node_point(aes(color = as.factor(c_mmuphin_s$cluster), shape = as.factor(meta$Y)),size = 0.5) + 
    theme_bw()+
  xlab("")+
  ylab("")+
  labs(title = "MMUPHin",subtitle = paste("ARI =",round(adjustedRandIndex(c_mmuphin_s$cluster,meta$Y), digits = 2)))+
 guides(color = "none", shape = guide_legend(title="Truth"))
```

```{r,warning=F}
set.seed(2024)
c_conqur_s = community_detection(res_conqur,K=50)
sample_res_conqur = as.factor(c_conqur_s$cluster)
p6 = ggraph(c_conqur_s$g, layout = "stress") + 
    geom_node_point(aes(color = as.factor(c_conqur_s$cluster), shape = as.factor(meta$Y)),size = 0.5) + 
    theme_bw()+
  xlab("")+
  ylab("")+
  labs(title = "ConQuR",subtitle = paste("ARI =",round(adjustedRandIndex(c_conqur_s$cluster,meta$Y), digits = 2)))+
  guides(color = "none", shape = guide_legend(title="Truth"))
```


```{r}
library(ggpubr)
ggarrange(p1,p3,p4,p5,p6,common.legend = TRUE,nrow=1,legend="bottom")
#ggsave("../fig/sample_cluster_newmethod.jpeg", dpi=300, units="in", width=10, height=2.5)
```

## Fig S6

```{r}
library(RColorBrewer)
library(pheatmap)
heatmap_plot = function(X,diff_set,Y,main){
  data_D = as.data.frame(t(X))
  rownames(data_D) = sapply(1:nrow(data_D),function(i)paste("Sample",i))
  colnames(data_D) = sapply(1:ncol(data_D),function(i)paste("Taxon",i))
  
  data_D = data_D[,order(diff_set)]
  cluster.taxa = data.frame("Taxa" = diff_set[order(diff_set)])
  rownames(cluster.taxa) = colnames(data_D)
  
  data_D = data_D[order(Y),]
  cluster.sample = data.frame("Sample" = Y[order(Y)])
  rownames(cluster.sample) = rownames(data_D)
  
  Var1 = brewer.pal(8, "Set3")[5:(4+length(unique(Y)))]
  names(Var1) = unique(Y)
  Var2 = brewer.pal(8, "Set2")[1:length(unique(diff_set))]
  names(Var2) = unique(diff_set)
  ann_colors = list("Taxa" = Var2,"Subpopulation" = Var1)
  
  p1 = pheatmap(data_D, main = main, annotation_col = cluster.taxa, annotation_row = cluster.sample, cluster_rows = F, cluster_cols = F, show_colnames = F,show_rownames = F, annotation_colors = ann_colors, color = colorRampPalette(c( "deepskyblue4","floralwhite", "firebrick4"))(50))
  return(p1)
}
```


```{r}
X_t = do.call(cbind,data[[3]])
X_t1 = X_t/50
p1 = heatmap_plot(log(X_t1+0.5),diff_set,meta$Y,"Truth")
ggsave("../fig/truth_heatmap.jpeg", p1,dpi=300, units="in", width=8, height=6)
```

```{r}
taxa_c = sapply(taxa_res_metadict,function(x)paste("Estimated Community",x))
sample_c = sapply(sample_res_metadict,function(x)paste("Estimated Subpopulation",x))
p2 = heatmap_plot(log(X_t1+0.5),taxa_c,sample_c,"MetaDICT")
ggsave("../fig/metadict_heatmap.jpeg", p2,dpi=300, units="in", width=8, height=6)

```


```{r}
taxa_c = sapply(taxa_res_unprocessed,function(x)paste("Estimated Community",x))
sample_c = sapply(sample_res_unprocessed,function(x)paste("Estimated Subpopulation",x))
p3 = heatmap_plot(log(X_t1+0.5),taxa_c,sample_c,"Unprocessed")
ggsave("../fig/unprocessed_heatmap.jpeg", p3,dpi=300, units="in", width=8, height=6)

```

```{r}
taxa_c = sapply(taxa_res_combatseq,function(x)paste("Estimated Community",x))
sample_c = sapply(sample_res_combatseq,function(x)paste("Estimated Subpopulation",x))
p4 = heatmap_plot(log(X_t1+0.5),taxa_c,sample_c,"ComBatSeq")
ggsave("../fig/combatseq_heatmap.jpeg", p4,dpi=300, units="in", width=8, height=6)

```

```{r}
taxa_c = sapply(taxa_res_mmuphin,function(x)paste("Estimated Community",x))
sample_c = sapply(sample_res_mmuphin,function(x)paste("Estimated Subpopulation",x))
p5 = heatmap_plot(log(X_t1+0.5),taxa_c,sample_c,"MMUPHin")
ggsave("../fig/mmuphin_heatmap.jpeg", p5,dpi=300, units="in", width=8, height=6)

```

```{r}
taxa_c = sapply(taxa_res_conqur,function(x)paste("Estimated Community",x))
sample_c = sapply(sample_res_conqur,function(x)paste("Estimated Subpopulation",x))
p6 = heatmap_plot(log(X_t1+0.5),taxa_c,sample_c,"ConQuR")
ggsave("../fig/conqur_heatmap.jpeg", p6,dpi=300, units="in", width=8, height=6)
```



