```{r}
library(ggpubr)
library(dplyr)
library(ggraph)
library(stringr)
library(ggplot2)
library(reshape2)
library(scales)
library(viridis)
library(effsize)
library(MBESS)
library(MicrobiomeStat)
library(reshape2)
library(randomForest)
library(caret)
library(pROC)
```


```{r}
#load(url("https://github.com/AlessioMilanese/motus_taxonomy/blob/master/data/motus_taxonomy_2.5.1.Rdata?raw=true"))
load("../data/motus_taxonomy_2.5.1.Rdata")
```

```{r}
count = read.table("../data/3517209/species_profiles_g2_l75_motus2.0.0.tsv",sep='\t', stringsAsFactors = FALSE,
                        header = TRUE, check.names = FALSE, row.names = 1,
                        quote='')

meta = readr::read_tsv("../data/3517209/meta_all.tsv")
```

```{r}
include_study = c("FR-CRC","DE-CRC","CN-CRC","US-CRC","AT-CRC" )
meta <- meta %>%
  filter(Study %in% include_study) %>%
  filter(Group %in% c('CTR', 'CRC'))

meta$Group[meta$Group == "CTR"] = "Control"
all_taxonomy = motus2.5_taxonomy
count = count[,meta$Sample_ID]
```

```{r}
# adjust taxonomy format
taxonomy = str_split_fixed(rownames(count)," ",3)
taxonomy = as.data.frame(taxonomy)
colnames(taxonomy) = c("Genus","Species","OTU")
taxonomy$taxa = rownames(count)


taxonomy$Species[str_detect(taxonomy$taxa,"alpha proteobacterium")] = str_split_fixed(taxonomy$taxa[str_detect(taxonomy$taxa,"alpha proteobacterium")],"\\[",2)[,1]

select_taxa = which(str_detect(taxonomy$taxa,"alpha proteobacterium")==T)
for(i in select_taxa){
  taxonomy$Species[i] = str_trim(taxonomy$Species[i], "right")
  taxonomy$Genus[i] = all_taxonomy$Genus[str_detect(all_taxonomy$Species,taxonomy$Species[i])][1]
}

taxonomy$Species[str_detect(taxonomy$taxa,"butyrate-producing")] = str_split_fixed(taxonomy$taxa[str_detect(taxonomy$taxa,"butyrate-producing")],"\\[",2)[,1]
select_taxa = which(str_detect(taxonomy$taxa,"butyrate-producing")==T)
for(i in select_taxa){
  taxonomy$Species[i] = str_trim(taxonomy$Species[i], "right")
  taxonomy$Genus[i] = all_taxonomy$Genus[str_detect(all_taxonomy$Species,taxonomy$Species[i])][1]
}

taxonomy$Species[str_detect(taxonomy$taxa,"uncultured")] = str_split_fixed(taxonomy$taxa[str_detect(taxonomy$taxa,"uncultured")],"\\[",2)[,1]
select_taxa = which(str_detect(taxonomy$taxa,"uncultured")==T)
for(i in select_taxa){
  taxonomy$Species[i] = str_trim(taxonomy$Species[i], "right")
  if(taxonomy$Species[i]=="uncultured candidatus Thalassoarchaea euryarchaeot"){
    taxonomy$Genus[i] = "Euryarchaeota gen. incertae sedis"
  }else{
    taxonomy$Genus[i] = all_taxonomy$Genus[str_detect(all_taxonomy$Species,taxonomy$Species[i])][1]
  }
}

taxonomy$Genus[which(taxonomy$Genus=="unknown")] = taxonomy$Species[which(taxonomy$Genus=="unknown")]

select_taxa = which(taxonomy$Genus=="candidatus")
for(i in select_taxa){
  taxonomy$Species[i] = str_trim(taxonomy$Species[i], "right")
  if(str_detect(taxonomy$taxa[i],"unknown")){
    taxonomy$Species[i] = str_split_fixed(taxonomy$taxa[i],"\\[",2)[1]
    taxonomy$Genus[i] = gsub("unknown", "", taxonomy$Species[i])
  }else{
    taxonomy$Genus[i] = paste(taxonomy$Genus[i],taxonomy$Species[i])
  }
  taxonomy$Genus[i] = gsub("candidatus", "Candidatus", taxonomy$Species[i])
  taxonomy$Genus[i] = str_trim(taxonomy$Genus[i], "left")
  taxonomy$Genus[i] = str_trim(taxonomy$Genus[i], "right")
}

taxonomy$Genus = gsub("unknown ","",taxonomy$Genus)

select_taxa = which(taxonomy$Genus=="cand.")
for(i in select_taxa){
  taxonomy$Species[i] = str_trim(taxonomy$Species[i], "right")
  if(str_detect(taxonomy$taxa[i],"unknown")){
    taxonomy$Species[i] = str_split_fixed(taxonomy$taxa[i],"\\[",2)[1]
    taxonomy$Genus[i] = gsub("unknown", "", taxonomy$Species[i])
  }else{
    taxonomy$Genus[i] = paste(taxonomy$Genus[i],taxonomy$Species[i])
  }
  taxonomy$Genus[i] = gsub("candidatus", "Candidatus", taxonomy$Species[i])
  taxonomy$Genus[i] = str_trim(taxonomy$Genus[i], "left")
  taxonomy$Genus[i] = str_trim(taxonomy$Genus[i], "right")
}

taxonomy$Genus[which(taxonomy$Genus=="1730 Eubacterium")] = "Eubacterium"
taxonomy$Genus[which(taxonomy$Genus=="1485 Clostridium")] = "Clostridium"
taxonomy$Genus[which(taxonomy$Genus=="41275 Brevundimonas")] = "Brevundimonas"
taxonomy$Genus[which(taxonomy$Genus=="Candidatus Saccharibacteria")] = "Saccharibacteria"

taxonomy = taxonomy[taxonomy$Genus!="cellular",]
taxonomy$Genus[which(taxonomy$Genus=="bacterium")] = "Bacterium"
```

```{r}
#write.csv(taxonomy,"taxonomy.csv")
```

# Genus level analysis

```{r}
source("../function.R")
```

```{r}
count = as.data.frame(count)
genus.name = unique(taxonomy$Genus)
genus.name = genus.name[-length(genus.name)]

# aggregate taxa to genus level
count.genus = matrix(0,nrow = length(genus.name),ncol = ncol(count))
row_to_genus = lapply(genus.name,function(x)taxonomy$taxa[which(taxonomy$Genus==x)])
count.genus = sapply(1:length(genus.name),function(i)colSums(count[row_to_genus[[i]],]))
count.genus = t(count.genus)
rownames(count.genus) = genus.name
colnames(count.genus) = colnames(count)
count.genus = as.data.frame(count.genus)
count.genus = count.genus[(rowSums(count.genus)>0),]
```

```{r}
meta_sub = meta %>%
  select("Sample_ID","Age","Gender","BMI","Study","Group")
meta_sub = na.omit(meta_sub)

count.genus = count.genus[,meta_sub$Sample_ID]
meta_sub$Study = sapply(meta_sub$Study,function(x)strsplit(x,"-")[[1]][1])
```

# data integration

```{r}
include_study = c("FR","DE","CN","US","AT" )
sample_list = lapply(include_study,function(x)meta_sub$Sample_ID[which(meta_sub$Study==x)])
O.list = lapply(1:5,function(i)as.matrix(count.genus[,sample_list[[i]]]))
```

```{r}
rownames(meta_sub) = meta_sub$Sample_ID
meta_sub1 = meta_sub %>%
  select("Age","Gender","BMI","Group")
rownames(meta_sub1) = meta_sub$Sample_ID
```

```{r}
meta.list = lapply(1:5,function(i)meta_sub1[sample_list[[i]],])
```

```{r}
# distance based on taxonomy 
# dist(i,j) = 0 when i and j are from the same family; dist(i,j) = 1 for other
# pairs.
dist.genus = matrix(1,nrow=nrow(count.genus),ncol = nrow(count.genus))
wrong_g = c()
for(i in 1:nrow(count.genus)){
  name1 = rownames(count.genus)[i]
  f1 = all_taxonomy$Family[str_detect(all_taxonomy$Genus,name1)][1]
  if(is.na(f1)){
      next
    }
  for(j in 1:nrow(count.genus)){
    name2 =rownames(count.genus)[j]
    f2 = all_taxonomy$Family[str_detect(all_taxonomy$Genus,name2)][1]
    if(is.na(f2)){
      wrong_g = c(wrong_g,j)
    }else{
      if(f1 == f2){
        dist.genus[i,j] = 0
      }
    }
  }
}

is.null(wrong_g)
```

```{r}
alpha = 1
beta = 0.01
gamma = 1
metadict.res = metadict(O.list,alpha,beta,gamma,dist.genus,meta.list)
```

```{r}
X = metadict.res$X
```

# counfounding effect between batch 

```{r}
p_age = ggplot(meta_sub,aes(y = Age, x = Study, color = Study))+
  geom_boxplot()+
  scale_color_brewer(palette="Set1")+
   geom_jitter(size=alpha, alpha=0.3,width = 0.2)+
  theme_bw()

p_bmi = ggplot(meta_sub,aes(y = BMI, x = Study, color = Study))+
  geom_boxplot()+
    scale_color_brewer(palette="Set1")+
   geom_jitter(size=alpha, alpha=0.3,width = 0.2)+
  theme_bw()

p_gender = ggplot(meta_sub,aes(x = Study, group = Gender))+
  geom_bar(aes(fill = Gender, width = 0.2),position = "dodge")+
  geom_text(aes(label = ..count..), vjust = 1.5, position = position_dodge(.9),stat = "count",  colour = "white")+
  scale_fill_brewer(palette="Set2")+
  theme_bw()+
ylab("Count")

p_crc =  ggplot(meta_sub,aes(x = Study, group = Group))+
 geom_bar(aes(fill = Group, width = 0.2),position = "dodge")+
  geom_text(aes(label = ..count..), vjust = 1.5, position = position_dodge(.9),stat = "count",  colour = "white")+
  theme_bw()+
ylab("Count")
```

```{r}
# S10 a
ggarrange(p_age,p_bmi,p_gender,p_crc,nrow=1)
ggsave("../fig/rd_batch_cov.jpeg", dpi=300, units="in", width=17, height=3)
```

# counfounding effect between study

```{r}
p_age = ggplot(meta_sub,aes(y = Age, x = Group, color = Group))+
  geom_boxplot()+
  scale_color_brewer(palette="Set1")+
   geom_jitter(size=alpha, alpha=0.3,width = 0.2)+
  theme_bw()

p_bmi = ggplot(meta_sub,aes(y = BMI, x = Group, color = Group))+
  geom_boxplot()+
    scale_color_brewer(palette="Set1")+
   geom_jitter(size=alpha, alpha=0.3,width = 0.2)+
  theme_bw()

p_crc = ggplot(meta_sub,aes(x = Group, group = Gender))+
  geom_bar(aes(fill = Gender, width = 0.2),position = "dodge")+
  geom_text(aes(label = ..count..), vjust = 1.5, position = position_dodge(.9),stat = "count",  colour = "white")+
  scale_fill_brewer(palette="Set2")+
  theme_bw()+
ylab("Count")
```

```{r}
# S10 b
ggarrange(p_age,p_bmi,p_gender,nrow=1)
ggsave("../fig/rd_crc_cov.jpeg", dpi=300, units="in", width=15, height=3)
```

# R2 analysis

## Before-analysis permanova of confounders.

```{r}
permanova <- function(P, Y, method = "bray") {
  if(method == "bray"){
    distP = bcdist(t(P))
  }else{
    distP = dist(t(P),method = "euclidean")
  }
  
  df.Y = as.data.frame(Y)
  Re = adonis2(distP~., data = df.Y)
  return(Re$R2[1])
}
```

```{r}
R2_mat = data.frame("all_before" = numeric(),"Variable" = character())
for(i in 2:ncol(meta_sub)){
  R2_mat[i-1,2] = colnames(meta_sub)[i]
  R2_mat[i-1,1] = permanova(count.genus,meta_sub[,i])
}
rownames(R2_mat) = R2_mat$Variable
```

```{r}
study = unique(meta_sub$Study)
for(j in 1:length(study)){
  for(i in 2:ncol(meta_sub)){
    Y = meta_sub[meta_sub$Study==study[j],i]
  
    if(nrow(unique(Y))!=1){
      R2_mat[(i-1),(j+2)] = permanova(count.genus[,meta_sub$Study==study[j]],Y)
    }else{
      R2_mat[(i-1),(j+2)] = NA
    }
  }
}
R2_mat$all_after = sapply(2:6,function(i)permanova(X,meta_sub[,i]))
```

```{r}
colnames(R2_mat) = c("All (Unprocessed)", "ID",study,"All (MetaDICT)")
rownames(R2_mat)[5] = "CRC/Control"
R2_mat$ID = rownames(R2_mat)
```

```{r}
gg <- melt(R2_mat, id="ID")
gg$R2 = as.numeric(gg$value)
gg$ID = factor(gg$ID,levels = c("CRC/Control","Age","BMI","Gender","Study"))
gg$variable = factor(gg$variable,levels=c("All (MetaDICT)","All (Unprocessed)", study))
```

```{r}
# fig 6a
ggplot(gg, aes(y=ID,x=variable,fill=R2,label = percent(R2,accuracy = 0.01)))+
  geom_tile()+
  geom_text(col = "black",na.rm=T) +
  scale_fill_gradient(high = "#547298",low = "#DADEE7",na.value = "white") +
  xlab("") + 
  ylab("")+
  theme_bw()+
  theme(axis.text.x = element_text(face="bold"),
        axis.text.y = element_text(face="bold"),
        legend.position="none")+
  coord_fixed()
ggsave("../fig/rd_r2.jpeg",dpi=300,units="in", width=9, height=6)
```

## PCoA plots

```{r}
p4 = pcoa.plot.discrete(count.genus,meta_sub$Study,"Study (Unprocessed)")
p4_1 = pcoa.plot.discrete(X,meta_sub$Study,"Study (MetaDICT)")
p5 = pcoa.plot.discrete(count.genus,meta_sub$Group,"Group (Unprocessed)")
p5_1 = pcoa.plot.discrete(X,meta_sub$Group,"Group (MetaDICT)")
```

```{r}
# fig 6b
ggarrange(p4,p4_1,nrow = 1)
ggsave("../fig/rd_pcoa_batch.jpeg",dpi=300, units="in", width=9, height=3)

ggarrange(p5,p5_1,nrow = 1)
ggsave("../fig/rd_pcoa_crc.jpeg",dpi=300, units="in", width=9, height=3)
```

# Community detection
## Taxa community detection

```{r}
library(igraph)
taxa_groups = function(cluster.res){
  function_group = list()
  for(i in 1:length(unique(cluster.res))){
    function_group[[i]] = rownames(count.genus)[cluster.res==i]
  }
  return(function_group)
}
```

```{r}
D = metadict.res$D
res = community_detection(D[,1:50], K=2, method = "Walktrap", min_k = 2)
cluster.res = res$cluster
function_group = taxa_groups(cluster.res)
```

```{r}
edges =E(res$graph)
edge_node = c(0,0)
for(i in 1:length(edges)){
  edge_node = rbind(edge_node,ends(res$graph, edges[i]))
}
edge_node = edge_node[-1,]
```

```{r}
set.seed(2010)
color_list = c(
  "dodgerblue2",  # bright blue
  "#E31A1D",      # bright red
  "green4",       # dark green
  "#6A3D9A",      # purple
  "#FF7F00",      # orange
  "gold1",        # bright yellow
  "skyblue2",     # light blue
  "#FB9A99",      # light pink
  "palegreen2",   # pale green
  "#CAB2D6",      # light purple
  "#FDBF6F",      # light orange
  "gray70",       # light gray
  "khaki2",       # khaki
  "maroon",       # dark red
  "orchid1",      # orchid
  "deeppink1",    # deep pink
  "blue1",        # deep blue
  "steelblue4",   # dark steel blue
  "turquoise",    # turquoise
  "green1",       # bright green
  "yellow4",      # dark yellow
  "yellow3",      # medium yellow
  "darkorange4",  # dark orange
  "brown1",       # brown
  "#FF69B4",      # hot pink
  "#8B0000",      # dark red
  "#4682B4",      # steel blue
  "#9ACD32",      # yellow green
  "#B22222",      # firebrick red
  "#8A2BE2",      # blue violet
  "#FF4500",      # orange red
  "green3",       # bright green
  "blue4"         # cadet blue
)
v_color = sapply(cluster.res,function(i)color_list[i])

graphNetwork = res$graph

V(graphNetwork)$color <- adjustcolor(v_color, alpha.f = .8)

# Set edge colors
E(graphNetwork)$color <- adjustcolor("DarkGray", alpha.f = .5)

E(graphNetwork)$width <- 0.5

# Set edges with radius
E(graphNetwork)$curved <- 0.5
# Size the nodes by their degree of networking (scaled between 5 and 15)
V(graphNetwork)$size <- scales::rescale(log(degree(graphNetwork)), to = c(5, 10))

# Define the frame and spacing for the plot
par(xpd=T, mar=c(0,0,0,0))
jpeg("../../../../manuscript/fig/rd_taxa_community.jpeg", width = 12, height = 8, units = 'in', res = 500)
plot(
  graphNetwork,				
  layout = layout.fruchterman.reingold,	# Force Directed Layout 
  # = paste(coocTerm, ' Graph'),
  vertex.label.family = "sans",
  vertex.label.cex = 0.2,
  vertex.shape = "circle",
  vertex.label.dist = 0,			# Labels of the nodes moved slightly
  vertex.frame.color = adjustcolor("darkgray", alpha.f = .5),
  vertex.label.color = 'black',		# Color of node names
  vertex.label.font = 1,			# Font of node names
  vertex.label = rownames(count.genus),		# node names
  vertex.label.cex = 1 # font size of node names
)
legend("bottomleft",inset=c(0.78,0),legend = sapply(unique(cluster.res),function(i)paste("Microbial Community",i))[order(unique(cluster.res))], fill = color_list[1:16][order(unique(cluster.res))])
dev.off()
```

```{r}
genus.name$Family = sapply(genus.name$`rownames(count.genus)`,function(i)all_taxonomy$Family[str_detect(all_taxonomy$Genus,i)][1])
genus.name$Order = sapply(genus.name$`rownames(count.genus)`,function(i)all_taxonomy$Order[str_detect(all_taxonomy$Genus,i)][1])
genus.name$Class = sapply(genus.name$`rownames(count.genus)`,function(i)all_taxonomy$Class[str_detect(all_taxonomy$Genus,i)][1])
genus.name$Phylum = sapply(genus.name$`rownames(count.genus)`,function(i)all_taxonomy$Phylum[str_detect(all_taxonomy$Genus,i)][1])

genus.name$cluster = cluster.res
genus.name$Class = sapply(genus.name$Class,function(i)stringr::str_split(i," ")[[1]][2])
genus.name$Class[is.na(genus.name$Class)] = "Unknown"

genus.name$Phylum = sapply(genus.name$Phylum,function(i)stringr::str_split(i," ")[[1]][2])
genus.name$Phylum[is.na(genus.name$Phylum)] = "Unknown"
genus.name$Phylum[which(!genus.name$Phylum %in% c("Firmicutes","Proteobacteria","Actinobacteria","Bacteroidetes","Fusobacteria","Chloroflexi"))] = "Others"
```

```{r}
shuffle_res = c()
for(i in 1:1000){
  test = sample(genus.name$Phylum,nrow(genus.name))
  shuffle_res = c(shuffle_res,mean(apply(edge_node,1,function(x)test[x[1]]==test[x[2]])))
}

mean(shuffle_res)
```

```{r}
mean(apply(edge_node,1,function(x)genus.name$Phylum[x[1]]==genus.name$Phylum[x[2]]))
```

## Sample cluster

```{r}
set.seed(2025)
R = do.call("cbind",metadict.res$R)
sample_cluster = community_detection(t(R),K = 150)
sample.res = sample_cluster$cluster
```

```{r}
# Fig 6d
subpop_plot = data.frame("Study" = as.character(), "Proportion" = as.numeric(), "Subpopulation" = as.character(), "ypos" = as.numeric(), "percentage" = as.numeric())
for(i in 1:5){
  Study = rep(include_study[i],4)
  prop = sapply(1:4,function(x)mean(sample.res[meta_sub$Study == include_study[i]]==x))
  Subpopulation = 1:4
  prop1 = prop[c(4,3,2,1)]
  ypos = cumsum(prop1)- 0.5*prop1
  pert = paste(round(prop1*100, 2), "%", sep="")
  subpop_plot = rbind(subpop_plot,cbind(Study,prop,Subpopulation,ypos,pert))
}

subpop_plot$prop = as.numeric(subpop_plot$prop)

subpop_plot$ypos = as.numeric(subpop_plot$ypos)

ggplot(data = subpop_plot, aes(x="", y = prop, fill = Subpopulation)) +
  geom_bar(stat="identity",
         width=1,
         color = "white") +
  coord_polar(theta="y",start = 0)+
  facet_wrap(~Study)+
  geom_text(aes(y = ypos,label = pert),color = "white",size = 3)+
  theme_bw()+
  ylab("Proportion")+
  xlab("Study")+
  theme_void()
#ggsave(paste0("../fig/subpop_study_prop.jpeg"), dpi=300,units="in",width=6, height=4)
```

```{r}
data = as.data.frame(t(X))
colnames(data) = rownames(count.genus)
library(randomForest)
nsg.rf = randomForest(data, as.factor(sample.res), importance = T)
importance = nsg.rf$importance
taxa_dom = sapply(1:4,function(i)which.max(importance[,i]))
taxa_dom
```

```{r}
# Fig 6g
p.list = list()
i = 1
for(j in taxa_dom){
  plot_data = data.frame("abundance" = X[j,],"Sample" = as.factor(sample.res))
  p.list[[i]] = ggplot(plot_data,aes(y = abundance, x = Sample,color = Sample))+
    geom_boxplot()+
    geom_jitter(aes(color = Sample), size=0.05, alpha=0.3,width = alpha)+
    theme_bw()+
    xlab(rownames(count.genus)[j])+
    ylab("Abundance")
  i = i+1
}

ggarrange(p.list[[1]],p.list[[2]],p.list[[3]],nrow=1,common.legend = T)
#ggsave("../fig/rd_taxa_box.jpeg", dpi=300,units="in",width=14, height=4)
```

# Differential abundance test

```{r}
alpha = 0.1
out1 = linda(X/mean(X)*mean(as.matrix(count.genus)),meta_sub,formula = "~Group+Age+Gender+BMI+Study",
           p.adj.method = "BH", alpha = alpha)
```

```{r}
p.anc.metadict = out1$output$GroupCRC$padj
diff.metadict = out1$output$GroupCRC$reject
```

```{r}
logfold.metadict = out1$output$GroupCRC$log2FoldChange
diff.status.metadict = rep("Not Differentially Abundant",length(diff.metadict))
diff.status.metadict[diff.metadict == T & logfold.metadict>0] = rep("More Abundant in CRC")
diff.status.metadict[diff.metadict == T & logfold.metadict<0] = rep("More Abundant in Control")
```

```{r}
set.seed(2010)
color_list = c(
  "dodgerblue2", 
  "green4",
  "#E31A1C")
order_list = unique(diff.status.metadict)
v_color = sapply(diff.status.metadict,function(i)color_list[which(order_list==i)])
graphNetwork = res$graph

# Assign colors to nodes (search term blue, others orange)
V(graphNetwork)$color <- adjustcolor(v_color, alpha.f = .8)

# Set edge colors
E(graphNetwork)$color <- adjustcolor("DarkGray", alpha.f = .5)
# scale significance between 1 and 10 for edge width
E(graphNetwork)$width <- 0.5

# Set edges with radius
E(graphNetwork)$curved <- 0.5
# Size the nodes by their degree of networking (scaled between 5 and 15)
V(graphNetwork)$size <- scales::rescale(log(degree(graphNetwork)), to = c(5, 10))

# Define the frame and spacing for the plot
par(mai=c(0,0,0,0)) 
jpeg("../fig/rd_taxa_diff.jpeg", width = 10, height = 8, units = 'in', res = 500)
plot(
  graphNetwork,				
  layout = layout.fruchterman.reingold,	# Force Directed Layout 
  vertex.label.family = "sans",
  vertex.label.cex = 0.2,
  vertex.shape = "circle",
  vertex.label.dist = 0,			# Labels of the nodes moved slightly
  vertex.frame.color = adjustcolor("darkgray", alpha.f = .5),
  vertex.label.color = 'black',		# Color of node names
  vertex.label.font = 1,			# Font of node names
  vertex.label = rownames(count.genus),		# node names
  vertex.label.cex = 1 # font size of node names
)
legend("bottomleft",inset=c(0.7,0),legend = unique(diff.status.metadict), fill = color_list[1:3])
dev.off()
```

```{r,warning=F}
out.1 = linda(O.list[[1]],meta.list[[1]],formula = "~Group+Age+Gender+BMI",
           p.adj.method = "BH", alpha = alpha)
out.2 = linda(O.list[[2]],meta.list[[2]],formula = "~Group+Age+Gender+BMI",
           p.adj.method = "BH", alpha = alpha)
out.3 = linda(O.list[[3]],meta.list[[3]],formula = "~Group+Age+Gender+BMI",
           p.adj.method = "BH", alpha = alpha)
out.4 = linda(O.list[[4]],meta.list[[4]],formula = "~Group+Age+Gender+BMI",
           p.adj.method = "BH", alpha = alpha)
out.5 = linda(O.list[[5]],meta.list[[5]],formula = "~Group+Age+Gender+BMI",
           p.adj.method = "BH", alpha = alpha)
```

```{r}
p.anc.1 = out.1$output$GroupCRC$padj
p.anc.2 = out.2$output$GroupCRC$padj
p.anc.3 = out.3$output$GroupCRC$padj
p.anc.4 = out.4$output$GroupCRC$padj
p.anc.5 = out.5$output$GroupCRC$padj
```

```{r}
diff.anc.1 = out.1$output$GroupCTR$reject
diff.anc.2 = out.2$output$GroupCTR$reject
diff.anc.3 = out.3$output$GroupCTR$reject
diff.anc.4 = out.4$output$GroupCTR$reject
diff.anc.5 = out.5$output$GroupCTR$reject
```

```{r}
pval1 = data.frame("genus" = rownames(count.genus),"MetaDICT" = p.anc.metadict)
pval1$'FR' = p.anc.1
pval1$'DE' = p.anc.2
pval1$'CN' = p.anc.3
pval1$'US' = p.anc.4
pval1$'AT' = p.anc.5
pval = pval1[rowSums(pval1[,2:7]<alpha)>0,]
```

```{r}
pval = pval[order(pval$MetaDICT),]
```

```{r}
# S11
gg1 <- melt(pval, id="genus")
gg1$qval = as.numeric(gg1$value)
gg1$significance = NA
for(i in 1:nrow(gg1)){
  if(gg1$qval[i]<0.001){
  gg1$significance[i] = "*"
}else if(gg1$qval[i]<0.01){
   gg1$significance[i] = "*"
}else if(gg1$qval[i]<alpha){
  gg1$significance[i] = "*"
}
}

# remove unknown species
gg1 = gg1[gg1$genus!="cand.",]
gg1 = gg1[gg1$genus!="bacterium",]

ggplot(gg1, aes(x = genus,y = variable,fill = qval,label = significance))+
  geom_tile()+
  geom_text(col = "black",na.rm=T) +
  scale_fill_gradient2(high = "#DA9599",low = "#F9EFEF") +
  xlab("") + 
  ylab("")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),legend.position = "bottom")+
  guides(fill=guide_colourbar(title="Adjusted p-value"))
#ggsave("../fig/rd_qval.jpeg",dpi=300,units="in", width=15, height=8)
```


# Prediction

```{r}
RF_pred = function(train,test,trainy,testy){
  control <- trainControl(method="repeatedcv", 
                        number=10, 
                        repeats=3,
                        classProbs = TRUE,
                        allowParallel = TRUE)
  dataset = data.frame(trainy,t(train))
  rf <- train(trainy~., data=dataset, 
                  method="rf", 
                  metric='Accuracy',
                  trControl=control,
                  ntree = 500)
    test_pred <- predict(rf, newdata = t(test))
  actual <- testy
  roc_object <- roc(actual,as.numeric(test_pred))
  return(auc(roc_object))
}
```

```{r}
X = data.frame(X)
rownames(X) = rownames(count.genus)
colnames(X) = colnames(count.genus)
```

```{r}
set.seed(2025)

rf.u = count.genus
rf.m = X

pred_res = rep(0,60)

data.u = list()
data.m = list()
y.list = list()
train = c()
type = c()
test = c()

for(i in 1:5){
  data.u[[i]] = rf.u[,which(meta_sub$Study==include_study[i])]
  data.m[[i]] = rf.m[,which(meta_sub$Study==include_study[i])]
  y.list[[i]] = meta_sub$Group[which(meta_sub$Study==include_study[i])]
}

pred_res = c()
for(i in 1:5){
  for(j in 1:5){
      pred_res = c(pred_res,RF_pred(data.u[[i]],data.u[[j]],as.factor(y.list[[i]]), as.factor(y.list[[j]])))
       train = c(train,include_study[i])
      test = c(test,include_study[j])
      type = c(type, "Unprocessed")
  }
}

for(i in 1:5){
  for(j in 1:5){
    pred_res = c(pred_res,RF_pred(data.m[[i]],data.m[[j]],as.factor(y.list[[i]]), as.factor(y.list[[j]])))
    train = c(train,include_study[i])
    test = c(test,include_study[j])
    type = c(type, "MetaDICT")
  }
}

for(j in 1:5){
  pred_res = c(pred_res,RF_pred(rf.u[,which(meta_sub$Study!=include_study[j])],data.u[[j]],as.factor(meta_sub$Group[which(meta_sub$Study!=include_study[j])]), as.factor(y.list[[j]])))
  train = c(train,"Integrated Data")
  test = c(test,include_study[j])
  type = c(type, "Unprocessed")
}

for(j in 1:5){
  pred_res = c(pred_res,RF_pred(rf.m[,which(meta_sub$Study!=include_study[j])],data.m[[j]],as.factor(meta_sub$Group[which(meta_sub$Study!=include_study[j])]), as.factor(y.list[[j]])))
  train = c(train,"Integrated Data")
  test = c(test,include_study[j])
  type = c(type, "MetaDICT")
}
```

```{r}
pred_ac_res = data.frame("AUCROC" = pred_res, "Train" = train, "Test" = test, "Type" = type)
pred_ac_res$AUCROC = as.numeric(pred_ac_res$AUCROC)
pred_ac_res$Train = factor(pred_ac_res$Train,levels = c("AT","CN","DE","FR","US","Integrated Data"))
```

```{r}
train_set = unique(pred_ac_res$Train)
auc_m = sapply(train_set,function(i)mean(pred_ac_res$AUCROC[pred_ac_res$Train==i&pred_ac_res$Test!=i&pred_ac_res$Type=="MetaDICT"]))
auc_u = sapply(train_set,function(i)mean(pred_ac_res$AUCROC[pred_ac_res$Train==i&pred_ac_res$Test!=i&pred_ac_res$Type=="Unprocessed"]))
pred_ac_res = rbind(pred_ac_res,data.frame("AUCROC" = auc_m,"Train" = train_set,"Type" = rep("MetaDICT",length(train_set)),"Test"=rep("Average",length(train_set))))
pred_ac_res = rbind(pred_ac_res,data.frame("AUCROC" = auc_u,"Train" = train_set,"Type" = rep("Unprocessed",length(train_set)),"Test"=rep("Average",length(train_set))))
pred_ac_res$Train = factor(pred_ac_res$Train,levels = c("AT","CN","DE","FR","US","Integrated Data"))
pred_ac_res$Test = factor(pred_ac_res$Test,levels = c("Average","AT","CN","DE","FR","US","Integrated Data"))
```

```{r}
diff = pred_ac_res$AUCROC[which(pred_ac_res$Type=="MetaDICT")] - pred_ac_res$AUCROC[which(pred_ac_res$Type=="Unprocessed")] 
mean(diff[!is.na(diff)]>0)
```

```{r}
pred_ac_res$AUCROC[which(pred_ac_res$AUCROC==1)] = NA
```

```{r}
pred_ac_res$diff = 0
pred_ac_res$diff[which(pred_ac_res$Type=="MetaDICT")] = diff
pred_ac_res$diff[which(pred_ac_res$Type=="Unprocessed")] = diff

pred_ac_res$fill[pred_ac_res$diff>0] = "high"
pred_ac_res$fill[pred_ac_res$diff<0] = "low"
pred_ac_res$fill[pred_ac_res$diff==0] = "same"
pred_ac_res$fill[is.na(pred_ac_res$AUCROC)] = NA
```

```{r}
# Fig 6f
ggplot(pred_ac_res, aes(y=Test,x=Train,fill=fill,label = round(AUCROC,digit = 3)))+
  geom_tile()+
  geom_text(col = "black",na.rm=T) +
  xlab("") + 
  scale_fill_brewer(palette="Set2",na.value = "white")+
  facet_wrap(~Type)+
  ylab("")+
  xlab("Training Data") + 
  ylab("Test Data")+
  theme_bw()+
  theme(axis.text.x = element_text(face="bold"),
        axis.text.y = element_text(face="bold"),
        legend.position="none")+
  coord_fixed()
ggsave("../fig/rd_random_forest_all.jpeg",dpi=300,units="in",width=10, height=5)
```



